"""Echte Sätze aus Agent-Entwürfen OHNE Erstattungsempfehlung, für die Zusage-Prüfung (UC6, Branch b, Lücke B2).

Quelle: UC4-Läufe v1–v3 (ai-uc-04-agents-mcp, evals/laeufe/<version>/<lauf>/antwortentwuerfe.jsonl, letzter Entwurf
je Lauf) und UC7-Läufe aus Neon (Stand 02.10.2026). Ausgewählt sind alle Sätze, die „erstatt“, „zurück“, „gutschr“,
„überweis“ oder einen Geldbetrag enthalten, also jeder Satz, den die Prüfung überhaupt treffen könnte. Sehr lange Sätze
sind bei der Auswahl auf 200 Zeichen gekürzt worden.

ZUSAGEN: die 7 Sätze, die eine Erstattung zusagen, obwohl der Agent keine empfohlen hat (alle Ticket T02, Ben K002,
behauptete Doppelbuchung bei nur einer Zahlung). Ziel: 7 von 7 erkannt.
KEINE_ZUSAGEN: korrekte Ablehnungen, Verweise auf Apple/Google, Preisangaben. Ziel: keiner erkannt.
"""

ZUSAGEN = [
    ("v1/T02_lauf1", "Falls es sich aber um eine echte doppelte Abbuchung handelt, erstatten wir den Betrag direkt auf dein Zahlungsmittel."),
    ("v1/T02_lauf2", "Falls ja, erstatten wir dir den doppelten Betrag sofort."),
    ("v1/T02_lauf3", "Falls das bestätigt wird, erstatten wir dir den doppelt belasteten Betrag vollständig."),
    ("v2/T02_lauf1", "Sollte es sich um eine echte doppelte Belastung handeln, erstatten wir den Betrag selbstverständlich vollständig."),
    ("v2/T02_lauf3", "Falls es tatsächlich zwei Abrechnungen gab, kümmern wir uns sofort um die Erstattung."),
    ("v3/T02_lauf2", "Dann erstatten wir dir den doppelt belasteten Betrag sofort."),
    ("v3/T02_lauf3", "Sollte es tatsächlich eine echte doppelte Abbuchung sein, werden wir den Betrag vollständig erstatten."),
]

KEINE_ZUSAGEN = [
    ("v1/T02_lauf3", "Wir prüfen das sofort in unserem Zahlungssystem und überprüfen, ob wirklich zwei Abbuchungen von je 6,99 USD in diesem Monat stattgefunden haben."),
    ("v1/T05_lauf1", "Zu der Erstattung: Leider können wir anteilige oder volle Erstattungen nur innerhalb von 14 Tagen nach Abschluss anbieten."),
    ("v1/T05_lauf2", "Zu deiner Frage zur anteiligen Erstattung: Leider ist das nicht möglich."),
    ("v1/T05_lauf2", "Nach unserer Erstattungsrichtlinie können Jahresabos nur innerhalb von 14 Tagen nach dem Kauf erstattet werden."),
    ("v1/T05_lauf3", "Leider kann ich für die Erstattung dem anteilig ein negatives Ergebnis mitteilen: Unsere Erstattungsrichtlinie für Jahresabos sieht vor, dass wir den Betrag nur innerhalb von 14 Tagen nach Kauf zurück"),
    ("v1/T05_lauf3", "Da dein Abo bereits über 14 Tage läuft, ist eine Erstattung leider nicht mehr möglich."),
    ("v1/T06_lauf1", "Ich verstehe, dass du dein Jahresabo zurückgeben möchtest."),
    ("v1/T06_lauf1", "Da du das Abo über den App Store (iPhone) gekauft hast, können wir die Erstattung leider nicht selbst verarbeiten."),
    ("v1/T06_lauf1", "Die gute Nachricht: Apple erstattet solche Käufe normalerweise problemlos innerhalb von 14 Tagen."),
    ("v1/T06_lauf1", "Wähle „Problem melden\" → „Ich möchte diese Zahlung nicht erstatten\""),
    ("v1/T06_lauf1", "Apple kümmert sich dann um die Erstattung (dauert normalerweise ein paar Tage)."),
    ("v1/T06_lauf2", "Bitte stelle deine Erstattungsanfrage direkt bei Apple über diese Seite: **reportaproblem.apple.com**"),
    ("v1/T06_lauf2", "Apple kümmert sich dann um die volle Rückerstattung."),
    ("v1/T06_lauf3", "über den App Store gekauft hast – das liegt noch gut innerhalb unserer 14-Tage-Frist für Erstattungen."),
    ("v1/T06_lauf3", "Allerdings können wir Käufe über den App Store technisch nicht selbst erstatten."),
    ("v1/T06_lauf3", "Bitte stelle deinen Erstattungsantrag direkt bei Apple:"),
    ("v1/T06_lauf3", "Dort kannst du das Abo-Abonnement als Problem melden und die Rückerstattung anfragen."),
    ("v1/T07_lauf3", "Die werden sich bei dir melden und eine Lösung mit dir besprechen – auch zur Erstattung der bisherigen Überzahlungen."),
    ("v1/T10_lauf1", "Falls Fragen auftauchen, schreib gerne zurück!"),
    ("v1/T11_lauf1", "Laut unserer Erstattungsrichtlinie können wir Jahresabos nur innerhalb von 14 Tagen nach dem Kauf vollständig erstatten."),
    ("v1/T11_lauf1", "Da dein Abo über Google Play läuft (nicht über unsere Systeme), können wir eine Erstattung technisch nicht selbst durchführen."),
    ("v1/T11_lauf1", "Du könntest aber direkt bei Google Play versuchen, eine Erstattung zu beantragen – Google Play hat hier seine eigenen Richtlinien."),
    ("v1/T11_lauf2", "Leider kann ich dir hier nicht helfen, weil zwei Dinge gegen eine Erstattung sprechen:"),
    ("v1/T11_lauf2", "Wir erstatten Jahresabos nur innerhalb von 14 Tagen nach dem Kauf – danach leider nicht mehr."),
    ("v1/T11_lauf2", "Wir können Zahlungen über Google Play technisch nicht selbst zurückbuchen."),
    ("v1/T11_lauf2", "Bitte beantrage die Erstattung direkt über Google Play."),
    ("v1/T11_lauf3", "Leider können wir dein Jahresabo nicht mehr erstatten – die Erstattungsfrist beträgt nur 14 Tage ab Kauf, und diese ist bereits vorbei."),
    ("v1/T11_lauf3", "Zusätzlich haben wir noch keine direkten Kontrollmöglichkeiten bei Google Play: Dein Abo wurde über die Android-App gekauft, weshalb du deine Erstattung direkt bei Google Play beantragen müsstest."),
    ("v1/T12_lauf1", "📱 **6,99 USD pro Monat** oder"),
    ("v1/T12_lauf3", "• **Monatlich:** 6,99 USD"),
    ("v1/T15_lauf1", "Zur Erstattung für diesen Monat: Leider können wir bereits begonnene Monate nicht zurückerstatten – das ist unsere Richtlinie, auch wenn die App wenig genutzt wurde."),
    ("v1/T15_lauf1", "Der Betrag von 6,99 USD für September wird daher nicht erstattet."),
    ("v1/T15_lauf2", "Danach wechselst du zurück zu Free."),
    ("v1/T15_lauf2", "Zur Erstattung: Nach unserer Richtlinie erstatten wir Monatsabos nicht, wenn der Abrechnungsmonat bereits begonnen hat."),
    ("v1/T15_lauf3", "Zur Erstattung: Nach unserer Richtlinie können bereits begonnene Abrechnungsmonate nicht erstattet werden, auch nicht anteilig."),
    ("v1/T15_lauf3", "Da dein aktueller Monat (08.09.–08.10.2026) bereits läuft, können wir dir diese Zahlung leider nicht zurückbuchen."),
    ("v2/T02_lauf2", "In unseren Daten sehe ich für September nur eine Buchung vom 03.09.2026 über 6,99 USD."),
    ("v2/T02_lauf2", "eine Erstattung prüfen können."),
    ("v2/T02_lauf3", "Ich habe deine Zahlungshistorie überprüft und sehe für September bisher nur eine Abbucha von 6,99 USD."),
    ("v2/T05_lauf1", "Eine anteilige Erstattung ist leider nicht möglich: Laut unserer Erstattungsrichtlinie können wir für Jahresabos nur **innerhalb von 14 Tagen nach Kaufdatum** den vollen Betrag erstatten."),
    ("v2/T05_lauf2", "**Zur anteiligen Erstattung:**"),
    ("v2/T05_lauf2", "Leider ist eine Erstattung nicht möglich."),
    ("v2/T05_lauf2", "Unsere Richtlinie sieht vor, dass wir Jahresabos nur innerhalb von 14 Tagen nach dem Kauf erstatten können."),
    ("v2/T05_lauf2", "Dein Abo hast du am 15.08.2026 abgeschlossen, die Anfrage für eine Erstattung kam aber am 24.09.2026 – also nach Ablauf dieser Frist."),
    ("v2/T05_lauf2", "Nach dieser Zeit können wir keine vollständigen oder anteiligen Erstattungen durchführen."),
    ("v2/T05_lauf3", "Leider kann ich dir eine Erstattung nicht gewähren, da Rückgaben nur innerhalb von 14 Tagen nach dem Kauf möglich sind."),
    ("v2/T06_lauf1", "Leider können wir Käufe, die über Apple oder Google Play abgewickelt werden, technisch nicht selbst erstatten."),
    ("v2/T06_lauf1", "Die gute Nachricht: Du kannst die Erstattung direkt bei Apple beantragen."),
    ("v2/T06_lauf2", "Ich verstehe, dass du dein Jahresabo zurückgeben möchtest."),
    ("v2/T06_lauf2", "Da es sich um einen App-Store-Kauf handelt, können wir die Erstattung technisch nicht selbst durchführen."),
    ("v2/T06_lauf2", "Apple kümmert sich um die Erstattung und wird dir den Betrag direkt zurück auf dein Apple-ID-Zahlungsmittel buchen (in der Regel 3–5 Werktage)."),
    ("v2/T06_lauf3", "Käufe über den App Store können wir technisch leider nicht selbst erstatten – das regelt Apple direkt."),
    ("v2/T06_lauf3", "Bitte wende dich direkt an Apple unter reportaproblem.apple.com und beantrage dort die Erstattung deines Jahresabos."),
    ("v2/T06_lauf3", "Bei Käufen innerhalb von 14 Tagen erstattet Apple normalerweise den vollen Betrag."),
    ("v2/T07_lauf1", "Das gekündigte Abo wird nicht erstattet."),
    ("v2/T09_lauf2", "Wenn doch noch Fragen auftauchen, schreib gern zurück."),
    ("v2/T11_lauf1", "**Zu spät:** Für Jahresabos erstatten wir nur innerhalb von 14 Tagen nach dem Kauf."),
    ("v2/T11_lauf1", "Wir können solche Käufe technisch nicht erstatten."),
    ("v2/T11_lauf1", "Geh auf https://play.google.com/store, melde dich an, geh zu „Zahlungen und Abos\" > „Abos\" und versuch, eine Erstattung anzufordern."),
    ("v2/T11_lauf2", "**Rückgabefrist abgelaufen:** Unser Jahresabo kannst du nur innerhalb von 14 Tagen nach dem Kauf zurückgeben."),
    ("v2/T11_lauf2", "**Google Play handhabt Erstattungen:** Da du über die Android-App (Google Play) gekauft hast, können wir die Erstattung nicht selbst bearbeiten."),
    ("v2/T11_lauf2", "- Dort kannst du um eine Erstattung anfragen"),
    ("v2/T11_lauf3", "Leider kann ich dir für dein Jahresabo keine Erstattung ermöglichen – aus zwei Gründen:"),
    ("v2/T11_lauf3", "Für Jahresabos erstatten wir den vollen Betrag nur innerhalb von 14 Tagen nach dem Kauf."),
    ("v2/T11_lauf3", "**Käufe über Google Play können wir nicht selbst erstatten:** Weil du dein Abo direkt über die Android-App und Google Play gekauft hast, können wir die Erstattung technisch nicht durchführen."),
    ("v2/T11_lauf3", "Dort kannst du eine Rückerstattung anfordern und Google bewertet deinen Antrag nach den Store-Richtlinien."),
    ("v2/T12_lauf2", "**Monatlich:** 6,99 USD"),
    ("v2/T12_lauf2", "**Jährlich:** 59 USD (das entspricht etwa 4,92 USD pro Monat – also knapp 30 % günstiger als monatlich)"),
    ("v2/T15_lauf1", "**Zur Erstattung:** Leider können wir Monatsabos nicht erstatten, wenn der Monat bereits begonnen hat."),
    ("v2/T15_lauf1", "Dein aktueller Monat läuft seit dem 08.09., daher ist eine Rückerstattung der 6,99 USD nicht möglich."),
    ("v2/T15_lauf2", "Ich verstehe, dass du das Geld für den September zurück möchtest."),
    ("v2/T15_lauf2", "Leider erlaubt unsere Erstattungsrichtlinie bei Monatsabos keine Rückerstattung für bereits begonnene Monate – auch nicht anteilig."),
    ("v2/T15_lauf2", "September begonnen, weshalb eine Erstattung der 6,99 USD nicht möglich ist."),
    ("v2/T15_lauf2", "Danach wird dein Konto auf die kostenlose Free-Version zurückgestuft, deine Daten bleiben erhalten."),
    ("v2/T15_lauf3", "Zur Erstattung für September: Laut unserer Richtlinie werden bei Monatsabos bereits begonnene Monate leider nicht erstattet, auch nicht anteilig."),
    ("v2/T15_lauf3", "Oktober, daher ist eine Rückerstattung nicht möglich."),
    ("v3/T02_lauf1", "Bei dir sehe ich derzeit nur eine Abbuchung von 6,99 USD am 3."),
    ("v3/T02_lauf2", "Ich habe dein Konto geprüft: Bei uns ist für September aktuell eine Buchung von 6,99 USD verzeichnet."),
    ("v3/T05_lauf1", "Leider kann ich dir keine anteilige Erstattung gewähren."),
    ("v3/T05_lauf1", "Laut unserer Erstattungsrichtlinie ist eine Rückzahlung für Jahresabos nur möglich, wenn die Anfrage innerhalb von 14 Tagen nach dem Kauf gestellt wird."),
    ("v3/T05_lauf2", "Leider kann ich dir eine anteilige Erstattung nicht gewähren: Laut unserer Erstattungsrichtlinie ist das nur innerhalb von 14 Tagen nach Kaufdatum möglich."),
    ("v3/T05_lauf3", "Zur anteiligen Erstattung: Nach unserer Erstattungsrichtlinie können wir beim Jahresabo nur innerhalb von 14 Tagen nach dem Kaufdatum eine Rückzahlung vornehmen."),
    ("v3/T05_lauf3", "Eine anteilige Erstattung ist daher nicht möglich."),
    ("v3/T06_lauf1", "Die gute Nachricht: Du befindest dich noch innerhalb der 14-Tage-Frist für eine Erstattung."),
    ("v3/T06_lauf1", "Da dein Kauf über den App Store erfolgte, können wir die Erstattung leider nicht selbst durchführen – das müssen die Stores direkt machen."),
    ("v3/T06_lauf1", "Apple kümmert sich dann um die Erstattung auf dein ursprüngliches Zahlungsmittel."),
    ("v3/T06_lauf2", "Wir können Käufe vom App Store leider technisch nicht selbst erstatten – das muss Apple direkt für dich übernehmen."),
    ("v3/T06_lauf2", "Bitte beantrage die Erstattung direkt bei Apple unter **reportaproblem.apple.com**."),
    ("v3/T06_lauf2", "Dort gibst du an, dass du FocusFlow Pro zurückgeben möchtest."),
    ("v3/T06_lauf2", "Apple bearbeitet das normalerweise zügig und erstattet auf dein Apple-Konto."),
    ("v3/T06_lauf3", "Ich verstehe, dass du das Jahresabo zurückgeben möchtest."),
    ("v3/T06_lauf3", "Da du dein Abo über Apples App Store gekauft hast, können wir die Erstattung leider technisch nicht selbst durchführen."),
    ("v3/T06_lauf3", "Die gute Nachricht: Apple erlaubt Rückgaben normalerweise noch bis zu 14 Tage nach dem Kauf – und dein Kauf liegt gerade mal 4 Tage zurück."),
    ("v3/T06_lauf3", "**So funktioniert es:** Bitte stelle deine Erstattungsanfrage direkt bei Apple unter **reportaproblem.apple.com**."),
    ("v3/T06_lauf3", "Apple folgt dann ihren eigenen Richtlinien und bearbeitet die Erstattung auf dein ursprüngliches Zahlungsmittel."),
    ("v3/T07_lauf1", "Schlechte Nachricht: Vorher musst du eines der Pro-Abos kündigen (der Kundenservice hat keine automatische Erstattung für das gekündigte Abo vorgesehen)."),
    ("v3/T07_lauf2", "Darüber, ob eine Erstattung infrage kommt, klären wir mit dir zusammen."),
    ("v3/T07_lauf3", "Wichtig zu wissen: Eine automatische Erstattung für das gekündigte Abo ist nicht vorgesehen – das Team wird dir aber alle Optionen durchsprechen."),
    ("v3/T11_lauf1", "Leider können wir eine Erstattung für dein Jahresabo leider nicht vornehmen, aus zwei Gründen:"),
    ("v3/T11_lauf1", "**14-Tage-Frist abgelaufen:** Wir erstatten Jahresabos vollständig nur innerhalb von 14 Tagen ab Kauf – dein Kauf liegt jetzt schon 6+ Monate zurück."),
    ("v3/T11_lauf1", "**Gekauft über Google Play:** Da du das Abo über die Android-App (Google Play) gekauft hast, können wir technisch nicht selbst erstatten."),
    ("v3/T11_lauf1", "Bitte wende dich direkt an Google Play und stelle dort einen Erstattungsantrag."),
    ("v3/T11_lauf2", "Leider kann ich dir bei einer Erstattung nicht weiterhelfen – dein Jahresabo wurde am 2."),
    ("v3/T11_lauf2", "März 2026 über Google Play gekauft, und unsere Erstattungsfrist beträgt nur 14 Tage nach dem Kauf."),
    ("v3/T11_lauf2", "Weil dein Abo über Google Play läuft, können wir es technisch nicht selbst erstatten."),
    ("v3/T11_lauf2", "Wenn du dennoch eine Rückerstattung möchtest, wende dich bitte direkt an Google Play – dort kannst du eine Anfrage einreichen und Google prüft das nach seinen Richtlinien."),
    ("v3/T11_lauf3", "Leider kann ich dir für dein Jahresabo keine Erstattung gewähren, da die 14-Tage-Frist (gezählt ab deinem Kaufdatum 02.03.2026) längst abgelaufen ist."),
    ("v3/T11_lauf3", "Nach unserer Richtlinie sind dann keine Erstattungen mehr möglich."),
    ("v3/T11_lauf3", "FocusFlow kann App-Store-Käufe technisch nicht selbst erstatten."),
    ("v3/T11_lauf3", "Wenn du dennoch eine Rückerstattung möchtest, wende dich bitte direkt an Google Play – dort gelten die Richtlinien des Stores, die teilweise großzügiger sind als unsere."),
    ("v3/T12_lauf2", "💰 **6,99 USD pro Monat** oder **59 USD pro Jahr** (das spart dir etwa 30 % gegenüber der monatlichen Zahlung)"),
    ("v3/T12_lauf3", "• 59 USD pro Jahr (das entspricht etwa 4,92 USD pro Monat und ist rund 30 % günstiger)"),
    ("v3/T15_lauf1", "Zur Erstattung für diesen Monat: Bei unseren Monatsabos können wir leider bereits begonnene Monate nicht erstatten, auch nicht anteilig."),
    ("v3/T15_lauf1", "gestartet ist, können wir die 6,99 USD nicht zurückbuchen."),
    ("v3/T15_lauf2", "Leider können wir für bereits begonnene Monate keine Erstattung gewähren – das ist unsere Richtlinie auch für Monate, die nicht aktiv genutzt werden."),
    ("v3/T15_lauf3", "Zur Erstattung: Nach unserer Richtlinie werden bereits begonnene Monate grundsätzlich nicht erstattet – auch nicht anteilig, selbst wenn die App nicht genutzt wurde."),
    ("uc7/20260928-190959-e0f2e4", "Zur Erstattung: Nach unserer Erstattungsrichtlinie können bereits begonnene Monate bei Monatsabos leider nicht erstattet werden – auch nicht anteilig."),
    ("uc7/20260929-052037-0865e4", "Leider kann ich dir keine gute Nachricht geben: Für Jahresabos erstatten wir den Betrag nur innerhalb von 14 Tagen nach dem Kauf."),
    ("uc7/20260929-052037-0865e4", "In diesem Fall können wir die Erstattung nicht selbst durchführen – da musst du dich direkt an Google Play wenden."),
    ("uc7/20260929-052037-0865e4", "Beantrage deine Erstattung hier: https://support.google.com/googleplay/answer/2479637"),
    ("uc7/20260930-105723-7279c9", "**Wichtig:** Wenn beide Konten gerade Pro-Abos haben, musst du eins davon vorher kündigen – eine automatische Erstattung erfolgt dabei nicht."),
]
